# Generated by Django 4.2.2 on 2023-07-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
