# Generated by Django 4.2.2 on 2023-07-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
    ]
